### ISSUE TITLE
What ROS section means in Readme.md ?

### ISSUE THREAD

**Issue by XinLong-Li** [zehuilu/How-to-Use-Qualisys-Motion-Capture-System#2]
Hi,
In the Readme.md file, there is a sentence:
> If you want to use Python 2 with ROS, please navigate to ROS section.

I am confused.  What do you mean?  There is no ROS section in you doc. 

Also I want to know if these scripts need to run on the seam computer which QTM is installed? The QTM computer is an Windows computer, how my another Ubuntu computer with ROS could get 6DoF data from this Windows computer.

Thank you!

**Comment by zehuilu** [comment]
Hi,

For the first question, this repository does not include contents related to ROS. I have updated the readme.

For the second question, you do not have to run these scripts on the same computer where QTM is running. Let's say the QTM computer is C1. And somehow you need to get mocap data on another computer C2. If C1 and C1 connect with the same network, you could do:
1) Use either C1 or C2 to run streaming or publisher script
2) Use C2 to run the subscriber script

From 1), notice that C1 does not need to run even one script. As long as QTM is running then you are fine. But it is okay to run the publisher on C1. Note that you could directly run the streaming script on C2 to get data and do your calculation within the same script. However, I would not recommend doing that since the running frequency of getting data and computation are not necessarily the same and this synchronous method has many issues for real-time usage. This is why I use the module asyncio in Python to do it asynchronously or concurrently.

For the third question, if you use TCP/IP, then I believe one publisher script needs to connect with one subscriber. If you use UDP, then many subscribers can connect with the same publisher. I think the bottleneck is the bandwidth of your network.
